include(":feature:settings_simple_manipulating_top")
include(":feature:settings_observed_directory")
include(":core")
include(":feature:feature_common")
include(":feature:settings_top")
include(":app", ":data")
